// <auto-generated />
namespace AlmacenListanco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2105_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2105_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210808226_21.05_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
